source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ScaledVisibleCellsCollectionView_Example', :exclusive => true do
  pod "ScaledVisibleCellsCollectionView", :path => "../"
end

target 'ScaledVisibleCellsCollectionView_Tests', :exclusive => true do
  pod "ScaledVisibleCellsCollectionView", :path => "../"
end
